NEMS/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NEMS.Data;
using NEMS.Helper;
using NEMS.Models;
using NuGet.Protocol;

namespace NEMS.Controllers
{
    [Authorize]
    public class CalendarController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IUserService _userService;

        public CalendarController(ApplicationDbContext db, IUserService userService)
        {
            _db = db;
            _userService = userService;
        }
        public IActionResult Index(CalendarModel calendarModel)
        {
            if (calendarModel.User == null)
            {
                calendarModel.User = _userService.getCurrentUser().Id;
            }

            calendarModel = getEvents(calendarModel);

            return View(calendarModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Schedule(CalendarModel calendarModel)
        {
            if (HttpContext.Request.Form["submit"] == "add")
            {
                ApplicationUser eventOwner = _userService.getCurrentUser();

                Event oEvent = new Event();
                oEvent.title = calendarModel.Event.title;
                oEvent.start = calendarModel.Event.start;
                oEvent.end = calendarModel.Event.end;
                oEvent.description = calendarModel.Event.description ?? "";
                oEvent.allDay = calendarModel.Event.allDay;
                oEvent.user = eventOwner.Id;
                oEvent.isOwner = true;

                _db.Events.Add(oEvent);
                _db.SaveChanges();

                int refId = oEvent.id;

                if (calendarModel.Participants != null)
                {
                    foreach (var participant in calendarModel.Participants)
                    {
                        Event pEvent = new Event();
                        pEvent.title = calendarModel.Event.title;
                        pEvent.start = calendarModel.Event.start;
                        pEvent.end = calendarModel.Event.end;
                        pEvent.description = calendarModel.Event.description ?? "";
                        pEvent.allDay = calendarModel.Event.allDay;
                        pEvent.user = participant;
                        pEvent.isOwner = false;
                        pEvent.refId = refId;

                        _db.Events.Add(pEvent);
                    }

                }
            }
            else if (HttpContext.Request.Form["submit"] == "edit")
            {
                Event editEvent = _db.Events.FirstOrDefault(x => x.id == calendarModel.Event.id);
                editEvent.title = calendarModel.Event.title;
                editEvent.start = calendarModel.Event.start;
                editEvent.end = calendarModel.Event.end;
                editEvent.description = calendarModel.Event.description ?? "";
                editEvent.allDay = calendarModel.Event.allDay;

                _db.Events.Update(editEvent);

                IEnumerable<Event> formalParticipants = _db.Events.Where(x => x.refId == calendarModel.Event.id);
                if (calendarModel.Participants != null)
                {
                    foreach (var participant in calendarModel.Participants)
                    {
                        if (formalParticipants.Any(x => x.user == participant))
                        {
                            Event pEvent = formalParticipants.FirstOrDefault(x => x.user == participant);
                            pEvent.title = calendarModel.Event.title;
                            pEvent.start = calendarModel.Event.start;
                            pEvent.end = calendarModel.Event.end;
                            pEvent.description = calendarModel.Event.description;
                            pEvent.allDay = calendarModel.Event.allDay;
                            _db.Events.Update(pEvent);
                        }
                        else
                        {
                            Event pEvent = new Event();
                            pEvent.title = calendarModel.Event.title;
                            pEvent.start = calendarModel.Event.start;
                            pEvent.end = calendarModel.Event.end;
                            pEvent.description = calendarModel.Event.description;
                            pEvent.allDay = calendarModel.Event.allDay;
                            pEvent.user = participant;
                            pEvent.isOwner = false;
                            pEvent.refId = calendarModel.Event.id;
                            _db.Events.Add(pEvent);
                        }
                    }
                }
                else
                {
                    calendarModel.Participants = new List<string>();
                }

                foreach (var participant in formalParticipants)
                {
                    if (!calendarModel.Participants.Any(x => x == participant.user))
                    {
                        _db.Events.Remove(participant);
                    }
                }
            }
            else if (HttpContext.Request.Form["submit"] == "delete")
            {
                IEnumerable<Event> deleteEvents = _db.Events.Where(x => x.id == calendarModel.Event.id || x.refId == calendarModel.Event.id);

                _db.Events.RemoveRange(deleteEvents);
            }
            else
            {
                //Something wrong happened
                return View("index", calendarModel);
            }

            _db.SaveChanges();

            calendarModel.User = _userService.getCurrentUser().Id;
            calendarModel = getEvents(calendarModel);

            return View("Index", calendarModel);
        }

        public CalendarModel getEvents(CalendarModel calendarModel)
        {
            calendarModel.Events = (from Event in _db.Events.Where(x => x.user == calendarModel.User)
                                    .Where(x => x.start.Date >= DateTime.Now.Date.AddYears(-1))
                                   select new
                                   {
                                       Event.id,
                                       Event.title,
                                       Event.start,
                                       Event.end,
                                       Event.allDay,
                                       Event.description
                                   }).ToList().ToJson();

            calendarModel.Users = _db.Users.Where(x => x.UserName != "th_accounting@nc-net.or.jp");

            return calendarModel;
        }
    }
}

NEMS/Controllers/LeaveController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NEMS.Data;
using NEMS.Helper;
using NEMS.Models;

namespace NEMS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LeaveController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IUserService _userService;
        public LeaveController(ApplicationDbContext db, IUserService userService)
        {
            _db = db;
            _userService = userService;
        }
        public IActionResult Index(LeaveModel leaveModel)
        {
            if(leaveModel.From == null)
            {
                leaveModel.User = _db.Users.FirstOrDefault(x => x.Id != _userService.getCurrentUser().Id).Id;
                leaveModel.From = DateTime.Now.AddMonths(-1);
                leaveModel.Until = DateTime.Now;
            }
            leaveModel.Users = _db.Users.Where(x => x.Id != _userService.getCurrentUser().Id);
            leaveModel.Leaves = _db.Events.Where(x => x.user == leaveModel.User)
                .Where(x => x.start >= leaveModel.From)
                .Where(x => x.end <= leaveModel.Until);

            return View(leaveModel);
        }
    }
}

NEMS/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NEMS.Data;
using NEMS.Helper;
using NEMS.Models;

namespace NEMS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserService _userService;

        public RolesController(RoleManager<IdentityRole> roleManager, ApplicationDbContext db, UserManager<ApplicationUser> userManager, IUserService userService)
        {
            _roleManager = roleManager;
            _db = db;
            _userManager = userManager;
            _userService = userService;
        }
        public IActionResult Index()
        {
            RoleModel roleModel = new RoleModel();

            roleModel = getUserRole(roleModel);

            return View(roleModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> editRoleAsync(RoleModel editRole)
        {
            if (HttpContext.Request.Form["submit"] == "edit")
            {
                ApplicationUser editUser = _db.Users.SingleOrDefault(x => x.Id == editRole.UserRole.uid);
                await _userManager.RemoveFromRolesAsync(editUser, await _userManager.GetRolesAsync(editUser));
                await _userManager.AddToRoleAsync(editUser, editRole.UserRole.RoleName);
            }

            editRole = getUserRole(editRole);

            return View("Index", editRole);
        }

        public RoleModel getUserRole(RoleModel roleModel)
        {
            List<ApplicationUser> users = _db.Users.Where(x => x.Id != _userService.getCurrentUser().Id).ToList();
            List<IdentityRole> roles = _db.Roles.Where(x => x.Name != "Admin").ToList();
            List<IdentityUserRole<string>> userRoles = _db.UserRoles.ToList();

            IEnumerable<UserRole> UserRoles =
                from user in users
                join userRole in userRoles on user.Id equals userRole.UserId
                join role in roles on userRole.RoleId equals role.Id
                select new UserRole
                {
                    uid = user.Id,
                    UserName = user.FirstName,
                    rid = role.Id,
                    RoleName = role.Name
                };

            roleModel.UserRoles = UserRoles;
            roleModel.Roles = roles;

            return roleModel;
        }
    }
}

NEMS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using NEMS.Data;
@using NEMS.Helper;
@inject SignInManager<ApplicationUser> SignInManager
@inject IUserService UserService
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NEMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NEMS.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NEMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Rules</a>
                            </li>
                            @if(User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clock" asp-action="AddPersonWorkTime">Add Person Work Time</a>
                                </li>
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="WorkTime" asp-action="Index">Summary</a>
                                </li>
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="WorkTime" asp-action="allSummary">Summary (All)</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Employee's Role</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Leave" asp-action="Index">Leave Management</a>
                                </li>
                            }else
                            {
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clock" asp-action="Clock">Clock in/out</a>
                                </li>
                                @if (User.IsInRole("Sales"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Clock" asp-action="AddTime">Add Time</a>
                                    </li>
                                }
                                <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="WorkTime" asp-action="CheckPersonalWorkTime">Check Work Time</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Schedule</a>
                            </li>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NEMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script type="text/javascript" src="~/js/multiselect.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $('#multiselect').multiselect();
        });
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>