NEMS/Controllers/WorkTimeController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Bibliography;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using NEMS.Data;
using NEMS.Helper;
using NEMS.Models;

namespace NEMS.Controllers
{
    [Authorize]
    public class WorkTimeController: Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IClockService _clock;
        private readonly IUserService _userService;

        public WorkTimeController(ApplicationDbContext db, UserManager<ApplicationUser> userManager, IClockService clock, IUserService userService, IEmailService emailService)
        {
            _db = db;
            _userManager = userManager;
            _clock = clock;
            _userService = userService;
        }

        //Return default worktime table for each user
        [Authorize(Roles = "Admin")]
        public IActionResult Index(SummaryViewModel summary)
        {
            //Provide default model data when first initialize WorkTime summary
            if (summary.From == null)
            {
                summary.Users = _db.Users.Where(x => x.Id != _userService.getCurrentUser().Id);
                summary.User = _db.Users.FirstOrDefault(x => x.Id != _userService.getCurrentUser().Id).Id;
                summary.TimeTables = _db.TimeTables.Where(x => x.date == DateTime.Today).Where(x => x.uid == summary.User);
                return View(summary);
            }

            summary = getQuery(summary);

            return View(summary);
        }

        //Check personal worktime for user not admin
        public IActionResult CheckPersonalWorkTime(SummaryViewModel summary)
        {
            if(summary.From == null)
            {
                summary.TimeTables = _db.TimeTables.Where(x => x.date == DateTime.Today)
                    .Where(x => x.uid == _userService.getCurrentUser().Id);
            }

            summary.TimeTables = _db.TimeTables.Where(x => x.date >= summary.From)
                .Where(x => x.date <= summary.Until)
                .Where(x => x.uid == _userService.getCurrentUser().Id)
                .OrderBy(x => x.date);

            return View(summary);
        }

        //Edit in/out time for specific user
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult editClock(SummaryViewModel summary)
        {
            if (HttpContext.Request.Form["submit"] == "edit")
            {
                TimeTable editRecord;
                editRecord = _db.TimeTables.FirstOrDefault(x => x.id == summary.Clock.id);
                editRecord = _clock.editWorkDay(editRecord, summary.Clock);

                _db.TimeTables.Update(editRecord);
                _db.SaveChanges();
            }
            else if (HttpContext.Request.Form["submit"] == "delete")
            {
                TimeTable deleteRecord;
                deleteRecord = _db.TimeTables.FirstOrDefault(x => x.id == summary.Clock.id);

                _db.TimeTables.Remove(deleteRecord);
                _db.SaveChanges();
            }
            else
            {
                //Something gone wrong if we get this far.
            }

            summary = getQuery(summary);

            return View("Index", summary);
        }

        //Add in/out time from missing day for specific user
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult addClock(SummaryViewModel summary)
        {
            summary.Clock.uid = summary.User;

            if (!_db.TimeTables.Any(x => x.date == summary.Clock.clockin.Date && x.uid == summary.Clock.uid))
            {
                summary.Clock = _clock.addWorkDay(summary.Clock);
                _db.TimeTables.Add(summary.Clock);
                _db.SaveChanges();
            }

            summary = getQuery(summary);

            return View("Index", summary);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult allSummary(AllSummaryModel allSummary, string submit)
        {
            if(allSummary == null)
            {
                allSummary.From = DateTime.Today;
                allSummary.Until= DateTime.Today;
                allSummary = getAllSummary(allSummary);
            }

            allSummary = getAllSummary(allSummary);

            if(submit == "export")
            {
                //Query range of time to export
                IEnumerable<TimeTable> timeTables = _db.TimeTables
                    .Where(x => x.date >= allSummary.From)
                    .Where(x => x.date <= allSummary.Until)
                    .OrderBy(x => x.date);

                //Get all users to reference writing in each sheet
                IEnumerable<ApplicationUser> users = _db.Users.Where(x => x.Id != _userService.getCurrentUser().Id);

                //Prepare file
                string format = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                string fileName = DateTime.Now.Date.ToShortDateString() + "_WorkTimeSummary.xlsx";

                //Create workbook and loop through each user/sheet
                using (var workbook = new XLWorkbook())
                {
                    foreach(var user in users)
                    {
                        //Set up date pointer
                        DateTime pointer = allSummary.From.Value;

                        //Get specific user in/out time from queried range above
                        IEnumerable<TimeTable> userTimeTables = timeTables.Where(x => x.uid == user.Id);
                        var worksheet = workbook.AddWorksheet(user.FirstName);
                        var currentRow = 1;
                        worksheet.Cell(currentRow, 1).Value = "Date";
                        worksheet.Cell(currentRow, 2).Value = "Clock in";
                        worksheet.Cell(currentRow, 3).Value = "Rounded";
                        worksheet.Cell(currentRow, 4).Value = "Clock out";
                        worksheet.Cell(currentRow, 5).Value = "Rounded";
                        worksheet.Cell(currentRow, 6).Value = "OT";
                        worksheet.Cell(currentRow, 7).Value = "ET";
                        worksheet.Cell(currentRow, 8).Value = "PayOT";

                        foreach(var day in userTimeTables)
                        {
                            while(day.date.Ticks > pointer.Date.Ticks)
                            {
                                currentRow++;
                                worksheet.Cell(currentRow, 1).Value = pointer.Date.ToShortDateString();
                                if (pointer.Date.DayOfWeek == DayOfWeek.Sunday || pointer.Date.DayOfWeek == DayOfWeek.Saturday)
                                {
                                    worksheet.Cell(currentRow, 1).Style.Font.SetFontColor(XLColor.Red);
                                }
                                pointer = pointer.AddDays(1);
                            }

                            if(day.date.Ticks == pointer.Date.Ticks)
                            {
                                currentRow++;
                                worksheet.Cell(currentRow, 1).Value = day.date.ToShortDateString();
                                if(day.date.DayOfWeek == DayOfWeek.Sunday || day.date.DayOfWeek == DayOfWeek.Saturday)
                                {
                                    worksheet.Cell(currentRow, 1).Style.Font.SetFontColor(XLColor.Red);
                                }
                                worksheet.Cell(currentRow, 2).Value = day.clockin.ToShortTimeString();
                                worksheet.Cell(currentRow, 3).Value = day.rClockin.ToShortTimeString();
                                worksheet.Cell(currentRow, 4).Value = day.clockout.ToShortTimeString();
                                worksheet.Cell(currentRow, 5).Value = day.rClockout.ToShortTimeString();
                                worksheet.Cell(currentRow, 6).Value = Math.Round(day.ot, 2);
                                worksheet.Cell(currentRow, 7).Value = Math.Round(day.et, 2);
                                worksheet.Cell(currentRow, 8).Value = Math.Round(day.ot, 2) - Math.Round(day.et, 2);
                                pointer = pointer.AddDays(1);
                            }
                            else
                            {
                                currentRow++;
                                //If we got here, something have gone wrong
                            }
                        }

                        while (pointer.Date.Ticks <= allSummary.Until.Value.Date.Ticks)
                        {
                            currentRow++;
                            worksheet.Cell(currentRow, 1).Value = pointer.Date.ToShortDateString();
                            if (pointer.Date.DayOfWeek == DayOfWeek.Sunday || pointer.Date.DayOfWeek == DayOfWeek.Saturday)
                            {
                                worksheet.Cell(currentRow, 1).Style.Font.SetFontColor(XLColor.Red);
                            }
                            pointer = pointer.AddDays(1);
                        }

                        //Sum ot, et, net ot at last row
                        worksheet.Cell(currentRow + 1, 6).Value = Math.Round(userTimeTables.Select(x => x.ot).Sum(),2);
                        worksheet.Cell(currentRow + 1, 7).Value = Math.Round(userTimeTables.Select(x => x.et).Sum(),2);
                        worksheet.Cell(currentRow + 1, 8).Value = Math.Round(userTimeTables.Select(x => x.ot).Sum() - userTimeTables.Select(x => x.et).Sum(),2);
                    }

                    //Store written workbook in variable content and return as a file

NEMS/Views/WorkTime/CheckPersonalWorkTime.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model SummaryViewModel;
@{
    DateTime countDay;
    DateTime countUntil;

    if(Model.From.HasValue)
    {
        countDay = Model.From.Value;
        countUntil = Model.Until.Value;
    }
    else
    {
        //If no value/page start, no conditions are met to loop empty days
        countDay = DateTime.Today;
        //-1 day in order to hide 1 auto generate leave row
        countUntil = DateTime.Today.AddDays(-1);
    }
}
<h1>Work Time Summary</h1>
<hr />
<div class="container">
    <div class="align-items-start">
        <div class="row">
            <div class="col-3">
                <form method="GET" asp-controller="WorkTime" asp-action="CheckPersonalWorkTime">
                    <input asp-for="From" class="form-control my-2" type="date" />
                    <input asp-for="Until" class="form-control my-2" type="date" />
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>

            </div>
            <div class="col-9">
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Date</th>
                            <th scope="col">Clock in</th>
                            <th scope="col">Clock in (Rounded)</th>
                            <th scope="col">Clock out</th>
                            <th scope="col">Clock out (Rounded)</th>
                            <th scope="col">Work Time</th>
                            <th scope="col">Over Time</th>
                            <th scope="col">Early Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var row in Model.TimeTables)
                        {
                            //countDay is less than rowDay assuming there's leave until this rowDay
                            //thus, looping through gap to generate leave row
                            while (row.date.Ticks > countDay.Ticks)
                            {
                                    <tr style="background-color:@(countDay.Date.DayOfWeek==DayOfWeek.Saturday||countDay.Date.DayOfWeek==DayOfWeek.Sunday ? "#FFCCCB" : "")">
                                        <td>@countDay.ToShortDateString()</td>
                                        <td colspan="7">Leave</td>
                                </tr>
                                countDay = countDay.AddDays(1);
                            }

                            //If countDay and rowDay are equal, normally print workday row
                            //Highlight red if clock in or out is missing by checking its default ticks value aka 0
                            if(row.date.Ticks == countDay.Ticks)
                            {
                                <tr>
                                    <td>@row.date.ToShortDateString()</td>
                                    <td>@row.clockin.ToShortTimeString()</td>
                                    <td>@row.rClockin.ToShortTimeString()</td>
                                    <td>@row.clockout.ToShortTimeString()</td>
                                    <td>@row.rClockout.ToShortTimeString()</td>
                                    <td>@String.Format("{0:N2}",row.worktime)</td>
                                    <td>@String.Format("{0:N2}",row.ot)</td>
                                    <td>@String.Format("{0:N2}",row.et)</td>
                                </tr>
                                countDay = countDay.AddDays(1);
                            }
                            else
                            {
                                <tr>
                                    <td>@countDay.ToShortDateString()</td>
                                    <td colspan="7">Duplicated</td>
                                </tr>
                            }
                        }

                        @while(countDay.Ticks <= countUntil.Ticks)
                        {
                            //Loop over when Until date is met
                            <tr style="background-color:@(countDay.Date.DayOfWeek==DayOfWeek.Saturday||countDay.Date.DayOfWeek==DayOfWeek.Sunday ? "#FFCCCB" : "")">
                                <td>@countDay.ToShortDateString()</td>
                                <td colspan="7">Leave</td>
                            </tr>
                            countDay = countDay.AddDays(1);
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

NEMS/Views/WorkTime/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model SummaryViewModel;
@{
    //Used for looping through empty/leave days along with workday
    DateTime countDay;
    DateTime countUntil;

    if(Model.From.HasValue)
    {
        countDay = Model.From.Value;
        countUntil = Model.Until.Value;
    }
    else
    {
        //If no value/page start, no conditions are met to loop empty days
        countDay = DateTime.Today;
        //-1 day in order to hide 1 auto generate leave row
        countUntil = DateTime.Today.AddDays(-1);
    }
}
<h1>Work Time Summary</h1>
<hr />
<div class="container">
    <div class="align-items-start">
        <div class="row">
            <div class="col-3">
                <form method="GET" asp-controller="WorkTime" asp-action="Index">
                    <select asp-for="User" class="form-select my-2">
                        @foreach(var user in Model.Users)
                        {
                            <option value="@user.Id">@user.FirstName</option>
                        }
                    </select>
                    <input asp-for="From" class="form-control my-2" type="date" />
                    <input asp-for="Until" class="form-control my-2" type="date" />
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>

            </div>
            <div class="col-9">
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Date</th>
                            <th scope="col">Clock in</th>
                            <th scope="col">Clock in (Rounded)</th>
                            <th scope="col">Clock out</th>
                            <th scope="col">Clock out (Rounded)</th>
                            <th scope="col">Work Time</th>
                            <th scope="col">Over Time</th>
                            <th scope="col">Early Time</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var row in Model.TimeTables)
                        {
                            //countDay is less than rowDay assuming there's leave until this rowDay
                            //thus, looping through gap to generate leave row
                            while(row.date.Ticks > countDay.Ticks)
                                {
                                <tr style="background-color:@(countDay.Date.DayOfWeek==DayOfWeek.Saturday||countDay.Date.DayOfWeek==DayOfWeek.Sunday ? "#FFCCCB" : "")">
                                    <td>@countDay.ToShortDateString()</td>
                                    <td colspan="6">Leave</td>
                                    <td>
                                        <button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#addModal" data-bs-date="@countDay.ToString("s")">Fill</button>
                                    </td>
                                </tr>
                                countDay = countDay.AddDays(1);
                                }

                                //If countDay and rowDay are equal, normally print workday row
                                //Highlight red if clock in or out is missing by checking its default ticks value aka 0
                            if (row.date.Ticks == countDay.Ticks)
                            {
                                <tr data-bs-toggle="modal" data-bs-target="#editModal"
                            data-bs-id="@row.id"
                            data-bs-date="@row.date.ToShortDateString()"
                            data-bs-in="@row.clockin.ToString("s")"
                            data-bs-out="@row.clockout.ToString("s")"
                                style="background-color:@(row.date.DayOfWeek==DayOfWeek.Saturday||row.date.DayOfWeek==DayOfWeek.Sunday ? "#FFCCCB" : "")">
                                    <td>@row.date.ToShortDateString()</td>
                                    <td style="color:@(row.clockin.Ticks==0 ? "red" : "")">@row.clockin.ToShortTimeString()</td>
                                    <td>@row.rClockin.ToShortTimeString()</td>
                                    <td style="color:@(row.clockout.Ticks==0 ? "red" : "")">@row.clockout.ToShortTimeString()</td>
                                    <td>@row.rClockout.ToShortTimeString()</td>
                                    <td>@String.Format("{0:N2}",row.worktime)</td>
                                    <td>@String.Format("{0:N2}",row.ot)</td>
                                    <td>@String.Format("{0:N2}",row.et)</td>
                                </tr>
                                countDay = countDay.AddDays(1);
                            }
                            else
                            {
                                <tr>
                                    <td>@countDay.ToShortDateString()</td>
                                    <td colspan="7">Duplicated</td>
                                </tr>
                            }
                        }

                        @while(countDay.Ticks <= countUntil.Ticks)
                        {
                            //Loop over when Until date is met
                            <tr style="background-color:@(countDay.Date.DayOfWeek==DayOfWeek.Saturday||countDay.Date.DayOfWeek==DayOfWeek.Sunday ? "#FFCCCB" : "")">
                                    <td>@countDay.ToShortDateString()</td>
                                    <td colspan="6">Leave</td>
                                    <td>
                                        <button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#addModal" data-bs-date="@countDay.ToString("s")">Fill</button>
                                    </td>
                                </tr>
                                countDay = countDay.AddDays(1);
                                }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" asp-controller="WorkTime" asp-action="editClock">
                <div class="modal-body">
                    <input type="hidden" class="id" asp-for="Clock.id">
                    <input type="hidden" asp-for="User" />
                    <input type="hidden" asp-for="From" />
                    <input type="hidden" asp-for="Until" />
                    <div class="mb-3">
                        <label class="form-label">Clock in</label>
                        <input type="datetime-local" step="any" class="in form-control" asp-for="Clock.clockin" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Clock out</label>
                        <input type="datetime-local" step="any" class="out form-control" asp-for="Clock.clockout" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" name="submit" value="edit">Edit</button>
                    <button type="submit" class="btn btn-danger" name="submit" value="delete">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var editModal = document.getElementById('editModal')
    editModal.addEventListener('show.bs.modal', function (event) {
        // Button that triggered the modal
        var tr = event.relatedTarget
        // Extract info from data-bs-* attributes
        var id = tr.getAttribute('data-bs-id')
        var date = tr.getAttribute('data-bs-date')
        var cin = tr.getAttribute('data-bs-in')
        var out = tr.getAttribute('data-bs-out')
        // If necessary, you could initiate an AJAX request here
        // and then do the updating in a callback.
        //
        // Update the modal's content.
        var editDate = editModal.querySelector('.modal-title')
        var editId = editModal.querySelector('.modal-body .id')
        var editIn = editModal.querySelector('.modal-body .in')
        var editOut = editModal.querySelector('.modal-body .out')

        editDate.textContent = 'Edit clock time of ' + date
        editId.value = id
        editIn.value = cin
        editOut.value = out
    })
</script>

        <!--Add time modal-->

<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" asp-controller="WorkTime" asp-action="addClock">
                <div class="modal-body">
                    <input type="hidden" asp-for="User" />
                    <input type="hidden" asp-for="From" />
                    <input type="hidden" asp-for="Until" />
                    <div class="my-2">
                        <input class="in form-control" type="datetime-local" step="any" asp-for="Clock.clockin" />
                    </div>
                    <div class="my-2">
                        <input class="out form-control" type="datetime-local" step="any" asp-for="Clock.clockout" />
                    </div>
                </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="submit">Submit</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
            </form>
        </div>
    </div>
</div>

<script>
    var addModal = document.getElementById('addModal')
    addModal.addEventListener('show.bs.modal', function (event) {

        var tr = event.relatedTarget

        var date = tr.getAttribute('data-bs-date')

        var addDate = addModal.querySelector('.modal-title')
        var addIn = addModal.querySelector('.modal-body .in')
        var addOut = addModal.querySelector('.modal-body .out')

        addDate.textContent = 'Add clock time of ' + date.replace("T00:00:00","")
        addIn.value = date.replace("T00:00:00", "T08:30:00")
        addOut.value = date.replace("T00:00:00", "T17:30:00")

    })
</script>

NEMS/Views/WorkTime/allSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model AllSummaryModel;
@{
}
<h1>All Summary</h1>
<hr />
<div class="container">
    <div class="align-items-start">
        <div class="row">
            <div class="col-3">
                <form method="get" asp-controller="WorkTime" asp-action="allSummary">
                    <label class="form-label" for="from">From</label>
                    <input type="date" asp-for="From" class="form-control my-2" id="from" />
                    <label class="form-label" for="until">Until</label>
                    <input type="date" asp-for="Until" class="form-control my-2" id="until" />
                    <div>
                        <button type="submit" class="btn btn-primary my-2" name="submit" value="query">Submit</button>
                        <button type="submit" class="btn btn-success" name="submit" value="export">Export</button>
                    </div>
                </form>
            </div>
            <div class="col-9">
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Over Time</th>
                            <th scope="col">Early Time</th>
                            <th scope="col">Pay OT</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var user in Model.Users)
                        {
                            <tr>
                                <td>@user.Name</td>
                                <td>@String.Format("{0:N2}",user.OT)</td>
                                <td>@String.Format("{0:N2}",user.ET)</td>
                                <td>@String.Format("{0:N2}",user.PayOT)</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>